### ISSUE TITLE
Add a note to the readme template about vagrant NFS shared folders.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#100]
The new vagrant bundled with the skeleton uses NFS for shared folders by default. This is because it is more performant overall, because Vagrant >1.6 handles NFS shares much more seamlessly, and because NFS shares work far better with VMware providers.

This does however cause vagrant to prompt for your Mac's admin password during `vagrant up` in order to modify your Mac's `/etc/exports` file appropriately, which is annoying. Thankfully, you can modify your system's `sudoers` config file to allow vagrant to execute only the commands it needs to edit the file on your behalf without prompting you for a password. Instructions for accomplishing this are even listed on the Vagrant website here ([Vagrant NFS Synced Folders](http://docs.vagrantup.com/v2/synced-folders/nfs.html)) under the **ROOT PRIVILEGE REQUIREMENT** heading towards the bottom of the page.

This change only needs to be made once on the host system, but this is kind of a "hidden" solution that's not very visible, so we should make the README we install into spawned projects include a note about this in the Developer setup section.

**Comment by ricog** [comment]
I have a script. What would you name such a script if put in the shell scripts repo?

**Comment by beporter** [comment]
A script to add the lines to your /etc/exports you mean? The preferred format is `noun-verb` ("the thing you're operating on", a dash, "the operation you're performing"), so something like `nfsexports-setsudoaccess`? I'm open to improvements.

**Comment by ricog** [comment]
That's perfect. ;) See why I asked? I'm actually going to use that since I
can't think of anything better. It is clear so... :+1:

On Thu, Mar 19, 2015 at 10:17 AM, Brian Porter <notifications@github.com>
wrote:

> A script to add the lines to your /etc/exports you mean? The preferred
> format is noun-verb ("the thing you're operating on", a dash, "the
> operation you're performing"), so something like nfsexports-setsudoaccess?
> I'm open to improvements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loadsys/CakePHP-Skeleton/issues/100#issuecomment-83622708>
> .
>



-- 
Rick Guyer
Project Manager
Loadsys Consulting Inc.
Email: rick@loadsys.com

**Comment by beporter** [comment]
Just by way of explanation (since the reasoning isn't actually documented anywhere):

I like this naming pattern because it logically groups the scripts into subject areas. I can type `bin/db[TAB]` on the command line, and get a list of all the actions I can perform related to the database. This is why the `run-codesniffer` and `run-tests` script names bother me; my mental context is on "unit tests" _first_. The next minor semver release should include this renaming (loadsys/CakePHP-Shell-Scripts#24) with placeholder scripts in place for a while to print a deprecation warning and proxy to the correct name.

**Comment by ricog** [comment]
Shell script started here: https://github.com/loadsys/CakePHP-Shell-Scripts/pull/46

**Comment by beporter** [comment]
Safe to close this, the script to make the changes exists in the Shell Scripts repo now.
