### ISSUE TITLE
Add Bootstrap UI to Cake 3.x Skeleton

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Skeleton#105]
https://github.com/FriendsOfCake/bootstrap-ui

**Comment by beporter** [comment]
Personally I'm split 50/50 on this. The new Foundation stuff looks pretty decent to my ignorant eyes. On the other hand, I like the idea of standardizing internally within Loadsys on Bootstrap as the default "prototyping" option for new apps (which are likely to be kick-started by this skeleton.) 

I'd love for someone to try to convince me either way.

**Comment by beporter** [comment]
Dropping this as Foundation will be enough of a solution.
