### ISSUE TITLE
Add another automated code-quality check to our list of tools?

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Skeleton#109]
Tool I read about today in [this book](https://leanpub.com/grumpy-testing): http://phpmd.org/documentation/index.html

It has a bunch of rules for basically trying to tell if your code is following a bunch of different rules, including things like SOLID, etc

http://phpmd.org/rules/index.html

I was able to get it built and running in a personal project in about 20 minutes. PR with this addition: https://github.com/jtyost2/secret/pull/57

Thoughts?

@beporter @ricog

**Comment by jtyost2** [comment]
The main ruleset is here: https://github.com/phpmd/phpmd/tree/master/src/main/resources/rulesets

Some of these are covered by our CodeSniffer, some aren't, overall though they look fine. We probably want to test it in an already developed app to see what it looks like.

**Comment by ricog** [comment]
Looks like it will add some value. I'm interested in trying it.

On Sat, Apr 25, 2015 at 10:03 PM, Justin Yost <notifications@github.com>
wrote:

> The main ruleset is here:
> https://github.com/phpmd/phpmd/tree/master/src/main/resources/rulesets
>
> Some of these are covered by our CodeSniffer, some aren't, overall though
> they look fine. We probably want to test it in an already developed app to
> see what it looks like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loadsys/CakePHP-Skeleton/issues/109#issuecomment-96313788>
> .
>



-- 
Rick Guyer
Project Manager
Loadsys Consulting Inc.
Email: rick@loadsys.com

**Comment by beporter** [comment]
Me too, although I'm always hesitant to further complicate the tool ecosystem we depend on. If there was a way to add these rules to `phpcs` directly, I would be in favor of that over pulling yet another analysis tool into the mix.

**Comment by jtyost2** [comment]
It does some rules that the code-sniffer probably couldn't have rules built for like, the Cyclomatic complexity, checks for tightly coupled classes, unused code, etc.

**Comment by jtyost2** [comment]
I'll try it in a Loadsys internal project and we can see how it works there.

**Comment by jtyost2** [comment]
Closing
