### ISSUE TITLE
Git Issue with the Baked Vagrant Box in 3.0 Branch

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Skeleton#119]
Output as a screenshot shown.

The git, current branch part of the ps listing doesn't work correctly.

![screen shot 2015-06-26 at 10 29 20 am](https://cloud.githubusercontent.com/assets/85320/8383353/4d75d6e8-1bee-11e5-97d5-f1442c64975b.png)

**Comment by beporter** [comment]
Thanks. Assign to me. I have a fix locally.
