### ISSUE TITLE
Should we build a Plugin for Loadsys CodeSniffed Templates?

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Skeleton#121]
I've kinda started down this path because it seems a hassle to bake stuff then have to hand edit everything to match Loadsys CodeSniff Standards.

Basic pattern to follow is this: http://book.cakephp.org/3.0/en/bake/development.html#creating-a-bake-theme

**Comment by beporter** [comment]
Yes we should. The skeleton should include that plugin out of the box, as well as perhaps a shortcut bake command that invokes the proper template set for us. (The template plugin should include the shell wrapper to do this; it can act like run-tests does for Cake2, where it passes through all additional args to `bin/cake bake`.)

**Comment by jtyost2** [comment]
Closed via: PR #123  and this Repo: https://github.com/loadsys/CakePHP-LoadsysTheme
