### ISSUE TITLE
Test Code Remaining In the Skeleton When Creating A Project

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Skeleton#126]
![screen shot 2015-07-01 at 12 49 58 pm](https://cloud.githubusercontent.com/assets/85320/8463519/c1f65e8e-1fef-11e5-896c-8af4c6eb5ae6.png)

**Comment by beporter** [comment]
There is an open issue for that already. In the context of the installer scripts themselves though.

**Comment by beporter** [comment]
Duplicates #72.
