### ISSUE TITLE
The forthcoming README needs to explain branch purposes.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#48]
The 3.0 (`master` branch) README.md (not the template version) needs to call out the `cake-2.x` branch and warn devs to target their PRs to the correct version of the skeleton. We also want to make sure it's clear that a full 2.x-compatible skeleton is still available in this repo and what branch to find that on.

This will obviously have to happen once Andrew has migrated the work from `loadsys/app`, so this depends on #47 being completed first.

**Comment by alecho** [comment]
I currently have it as a comment at the top of `README.md` does that work for you @beporter and will #54 close this issue?

**Comment by beporter** [comment]
Yeah, it's a start. It obviously won't show up when viewing the repo in Github's web interface though.
