### ISSUE TITLE
Better configuration handling

### ISSUE THREAD

**Issue by ricog** [loadsys/CakePHP-Skeleton#53]
I noticed while working with the new app a few things need to happen.

- [x] app-local.php should be ignored and checked for inclusion
- [x] app.php should not be ignored and included in the initial commit
- [x] an app-local.sample.php could be included as a starting point with common usage examples inside
- [x] APP_ENV needs to be set in bashrc (or equivalent) for shell scripts
- [x] app-local.php and app-{APP_ENV}.php should be conditionally checked

**Comment by beporter** [comment]
The first three will be largely addressed by #74.

**Comment by beporter** [comment]
#74 has been merged. Does it make sense to move the final item (setting the APP_ENV in the bash environment of the vagrant VM) out into its own Issue and close this one?

**Comment by ricog** [comment]
There's a bit more logic in the bootstrap.php file (added a 5th bullet). Let me wrap up something else and I'll see about including it.

**Comment by beporter** [comment]
Oh, you mean we're not actually loading the environment-specific or local configs yet, right? Yeah, good point there.

**Comment by ricog** [comment]
We are, but it isn't making sure the file exists before attempting to load
it. And if APP_ENV isn't set it fails too. I have the code here.

On Thu, Feb 12, 2015 at 5:20 PM, Brian Porter <notifications@github.com>
wrote:

> Oh, you mean we're not actually loading the environment-specific or local
> configs yet, right? Yeah, good point there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loadsys/CakePHP-Skeleton/issues/53#issuecomment-74175084>
> .
>



-- 
Rick Guyer
Project Manager
Loadsys Consulting Inc.
Email: rick@loadsys.com

**Comment by ricog** [comment]
I created #90 to handle the rest of this.
