### ISSUE TITLE
Import Test Suites?

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#59]
The 2.x skeleton had a number of test suites that "collected" like-types of files together (AllComponents, AllModels, AllCommands, etc). These were then composed into a master "All" suite that ran everything.

Based on [the docs](http://book.cakephp.org/3.0/en/development/testing.html#running-tests) this might not be necessary anymore since we're engaging phpunit directly. However, there may still be value in being able to determine the order of the tests and to test sub-groups of an app at will.

I'm open to debate.

**Comment by jtyost2** [comment]
Filtering is ok, but not a great solution for one simple reason:

1. Filtering requires a lot of typing to ensure you getting whatever correct test

**Comment by beporter** [comment]
Not as useful in Cake 3 as you can just target a file/dir directly using the `phpunit` shell directly.

Per discussion with @jtyost2 closing as not needed as much in Cake 3.x projects.
