### ISSUE TITLE
Import .gitignore, adapt as necessary.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#60]
The 2.x .gitignore file has a bunch of stuff we've run into over the years. We should evaluate it and pull over everything that might still be applicable.

**Comment by beporter** [comment]
Also obviously add stock versions of any files that were previously ignored.

**Comment by ricog** [comment]
I don't see much to transfer.

- OS generated files should be listed in your ~/.gitignore, not in each of your projects.
- /backups - not sure about this
- core-local.php will be handled in #53
- Composer is handled,
- /bin - not sure
- Vagrant is handled
- /webroot/assets - not sure what this is

So /node_modules is the only one I know needs added.

**Comment by beporter** [comment]
Some of those are going to be preemptive right now, but will eventually be necessary. I'd like to not have to remember to revisit the gitignore a half dozen more times.

* I have never used a ~/.gitignore. Makes some sense, but that should be documented in the wiki's New Employee Orientation or something since it's never going to be project-specific. There's no other way to make sure new devs get that set up **that way** and not just add it to every project's .gitignore they work on (like I have for 2.5 years).
* backups/ is used by shell scripts to save DB backups to.
* bin/ is the composer destination for the shell scripts. (This needs to be in the composer.json.template too.) I don't know if this will interfere with Cake's stuff, but I suspect they reached the same conclusion I did: that bin/ is better than vendor/bin.

**Comment by jtyost2** [comment]
Seconding not requiring a default `~/.gitignore`, while it may be in place in the Skeleton, we can ensure that all project will have this set of things covered, regardless of an employee's setup (which is kinda the whole goal - abstract away an employee having to deal with something).

**Comment by jtyost2** [comment]
Also `bin/` is not currently the composer destination in the Cake 3.0 Branch: https://github.com/cakephp/cakephp/blob/3.0/composer.json

We can set this and all scripts (PHPUnit, Cake, Shell Scripts, etc) that would normally go to `vendor/bin` instead are placed in the `bin/` and then that much less to type to use them, I like the `bin/` directory being used.

**Comment by beporter** [comment]
It's also what the Shell Scripts repo expects. The scripts need to be able to call each other in '/bin'.

**Comment by beporter** [comment]
> Seconding not requiring a default ~/.gitignore, while it may be in place in the Skeleton, we can ensure that all project will have this set of things covered, regardless of an employee's setup (which is kinda the whole goal - abstract away an employee having to deal with something).

Regarding this-- the list never changes much either, so even though yes, technically, it's duplicated in every project's .gitignore, it's not like it requires a ton of maintenance over time. I don't think I've ever had to touch that section in any of the files. It's just a "given." I agree that if we just leave it in the skeleton, it'll serve both as a reference and likely guarantee than a dev will never have to worry about a `~/.gitignore` either.

**Comment by ricog** [comment]
Re: `backups/` makes sense and should be added now.

Re: `bin/` we can, but cake.* scripts currently reside there too.

Re: arbitrary OS/editor specific ignores in the project .gitignore.

1. This seems sloppy. It's uneeded duplication and does not cover all developers/editors. If I start using a new editor, does it make more sense to add ignores to all the projects I work on, or just add them in one place (~/.gitignore).  What if developer A adds an ignore for their new wizbang editor that actually ignores some changes developer B intended to commit?

2. This can be remedied if you each copy the lines you care about into your ~/.gitignore. New developers learn quickly. My team doesn't put os/editor specific ignores into any of our projects.

3. I like to consider the .gitignore a reference for files that specifically exist in the project but do not get committed. The file makes more sense that way.

**Comment by beporter** [comment]
What editor-based files are covered? Seems just like OS stuff to me and that's not likely to change between devs.

I care less about some (minor) sloppiness at the top of this file than I do about alleviation of extra work. Like I said before, I've never bothered with a `~/.gitignore` and I don't *want* to have to think about what should go in which one. I also never want files to accidentally be excluded from a commit because they were in my "global" block file. The risk there seems _way_ worse that having the same seven or eight lines in a file that you can then safely ignore pretty much forever.

**Comment by beporter** [comment]
Justin kind of already made the bigger point though-- the goal is for the projects to be:

1. Self-sufficient. Everything the repo needs should be **in** the repo, not dependent on additional outside config.

2. Automatic. Again, we're trying to make **less** work for devs, not more. Including everything that's appropriate in the stock gitignore means I don't **have** to set up a local .gitignore _in addition to_ the repo's. I'd rather have the duplication than to accidentally start commiting `.DS_Store` files and having to clean that up!

3 Self-documenting. Nowhere in any of the repos does it explain that you should put "dev-specific" ignores in your own file. But if you're going to put THAT in every repo to try to avoid mistakes, why not just put the _actual_ ignores instead and be done? Again; more work, and it's opaque (your commits can be "wrong" because of something outside of what you see in the project itself).

**Comment by ricog** [comment]
It's really not that hard. `vim ~/.gitignore`. ;) Also, the only thing in that list I've ever needed to ignore was `.DS_Store`.

**Comment by beporter** [comment]
The point is not how difficult it is to do, it's having to remember to do it. The whole point of having our own skeleton is to do more for us out of the box so we don't have to keep wasting our own time and effort repeating the same things for every project. This may just be one additional step, but it's still _one additional step_ I don't think we need to impose on anyone. :-\

**Comment by jtyost2** [comment]
The OSX .gitignore as suggested by Github is way longer than that, though: https://github.com/github/gitignore/blob/master/Global/OSX.gitignore

And you say it isn't hard, but it's one more thing we can do now that we won't have to ever deal with in the future.

**Comment by beporter** [comment]
First. :+1:

**Comment by ricog** [comment]
If you two insist on having them in there please keep them at the bottom, separated from the actual ignored project files.

**Comment by beporter** [comment]
Even there we disagree, since I prefer to go progressively from most generic to most specific as you read down, but I can live with that as long as the headings remain in place.

**Comment by beporter** [comment]
(My excuse is that it makes it easier to diff if only the tail of the file changes on a per-project basis.)

**Comment by jtyost2** [comment]
PR issued with this change with the OSX stuff at the bottom as requested: https://github.com/loadsys/CakePHP-Skeleton/pull/63
