### ISSUE TITLE
Meta: `create-project` needs to do (at least) everything `skelbin/spawn` did for 2.x.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#66]
This isn't a specific task, but more of a reminder that we should try to reach feature parity with the old `skelbin/spawn` command in terms of post-processing the skeleton.

The new composer post-install scripts already have a leg up thanks to the token replacement, but I want to make sure we're still doing all of the old busywork that was previously automated for you. A quick scan of `spawn` and comparing it to what the core team's post-install script does, plus what Andrew's does, should do the trick.

**Comment by beporter** [comment]
As an example, `spawn` removes itself from the resulting project. Our post-install scripts should do the same thing since they should be irrelevant once the new project is created. Anything we'd want to be run repeatedly on an existing project should be a shell script instead so it's easily install-able and update-able.

That's no to say the `create-project` command couldn't run a shell script _for us_ of course as an initial startup task.

**Comment by beporter** [comment]
Another example: The `spawn` command would `git init` the new project for you, and even add a default git remote if you provided one. The new skeleton should do this as well.

**Comment by alecho** [comment]
I'm going to add issues for these if you haven't already.

**Comment by alecho** [comment]
If you want to close this issue and add any additional tasks from 2.x that need to be done as their own issue I think I would help others (read: me) see what needs to be done and assign themselves to issues.

**Comment by beporter** [comment]
In #67 I added all of the additional incomplete tasks as `TODO` markers in the updated README. That can now be the definitive list of "what's left" as far as I'm concerned.
