### ISSUE TITLE
Token replace the IP address in config.yaml

### ISSUE THREAD

**Issue by ricog** [loadsys/CakePHP-Skeleton#69]
It is currently hard coded to192.168.33.55, but needs to be unique per install. It would be nice if it can assign or recommend an IP.

Andrew and I have discussed a simple IP registry that the post install can use to assign IPs to new projects. The downside is this would need to be hosted somewhere. (loadsysdev?)

Optionally we could configure the post install to choose a 192.168.x.x randomly from a range. This should give us more than 60,000 possibilities even if we limit the range a bit to avoid conflicting with common home network ranges. So the chance of a conflict is pretty small and could be easily changed if it did.

**Comment by beporter** [comment]
Id like to come up with a hashing mechanism that pretty reliably chooses a random number between 2 and 254 for a given hostname or project name. The post install script should be able to "guess" an unused ip in a single subnet for a goo long time before we'd ever start having frequent collisions (which could always be corrected by hand anyway.)

I don't want to have to take a survey of all our existing VM IPs every time we start a new project, and I don't want to have to keep a list to refer to somewhere. Guessing with a good random spread seems reasonable to me.

**Comment by beporter** [comment]
I didn't emphasize well that the key point is that the IP resulting from the hostname (or whatever) is deterministic. The same input name always produces the same resulting IP.

**Comment by alecho** [comment]
in this scenario guessing seems like an easier solution but I would like to see more possibilities than 253

**Comment by beporter** [comment]
We're going to have to choose our possible ranges carefully then. My internal network is `192.168.42.x`, which collides with the range Rich suggested earlier.

**Comment by beporter** [comment]
So does the extremely common `192.168.0.x`/`192.168.1.x` from Linksys and Netgear, and `192.168.254.x` that a lot of 2wire's use.

**Comment by alecho** [comment]
How common is the 172.16.0.0 - 172.31.255.255 range? That give 1,048,576 addresses and I don't know of anything that uses that. I think Apple's routers ship with something in the 10.x.x.x range.

**Comment by beporter** [comment]
It's pretty common for corporate networks since the range is nice and large, but that shouldn't effect **us** too much.

**Comment by alecho** [comment]
Can we agree to use 172.31.0.0 - 172.31.255.255 then?

**Comment by ricog** [comment]
:+1: here

**Comment by beporter** [comment]
Yeah but obviously IPs can't end in `0` and should not end in `255` (which is typically a multicast address for the subnet.) So your range needs to exclude those IPs from each 4th octet.

**Comment by beporter** [comment]
In other words:
```
172.16.0.1 - 172.16.0.254
172.17.0.1 - 172.16.0.254
...
```

**Comment by alecho** [comment]
Thanks for catching that. Should be easy enough to implement. @ricog, you're ok with random IPs for VMs?

**Comment by beporter** [comment]
A class B subnet should be more than enough. I recommend locking the first two octets and only randomizing the last two. `172.20.x.x`. I'd still like a deterministic algorithm instead of truly random, but hey, baby steps.

**Comment by ricog** [comment]
At this point I'm happy with anything automatic.

**Comment by alecho** [comment]
@beporter Yeah see my comment about the range above.

**Comment by beporter** [comment]
Roger, I missed that you had explicitly defined 172.16.31.x in your example.

**Comment by beporter** [comment]
For now, I've set up the IP as a token replacement in #74. Should we open a new "Enhancement" issue for someday adding the randomly assigned IP?

**Comment by beporter** [comment]
See also: loadsys/composer-plugins#1
