### ISSUE TITLE
PostInstall script to adjust composer.json?

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#70]
So the skeleton needs to have a composer.json so it can be available through Packagist to use with `composer create-project`. But some of the items defined in the `composer.json` file are not accurate for a freshly created project using this method. I think we're going to need a post-install-cmd that rewrites the composer.json file to make (at least) the following corrections:

* `name`: From `loadsys/skeleton` to `loadsys/client-project-name` (dynamic for each run)
* `description`: From the skeleton's description to one appropriate for the new client project. (dynamic for each run)
* `type`: From `project` (which is what's used with `create-project`) to `library` to define the new client app as a standalone "endpoint". (Does composer change this for us maybe? Needs investigation.)
* `license`: From `MIT` (which is what we're apparently releasing our version of the skeleton under) to `proprietary` (which better describes the default circumstances for most of the projects we start.)
* `scripts:post-install-cmd`: I don't know how `create-project` works, but it seems like this stuff would hang around in a newly created project. If a new dev on that project then runs `composer install`, are those post-install-cmds going to run again for them? That seems incorrect since we don't want each dev setting up the project to have their own security salt, replace their own tokens (which should all be replaced already) etc. This probably needs to get removed on the initial `create-project` so the scripts are not repeated. (This is also why things like setting writeable directories are not best served in a composer post-install script but rather as something that can keep being called.)

**Comment by beporter** [comment]
It may help to think about this a little more abstractly? Are these all things people are going to have to change if they use the Cake core teams `cakephp/app` repo? How are they handling this in their documentation? Are they even?

**Comment by beporter** [comment]
There is another composer command target named `post-create-project-cmd`. Is that more appropriate for us?

**Comment by jtyost2** [comment]
Re: It may help to think about this a little more abstractly. Are these all things people are going to have to change if they use the Cake core team's cakephp/app repo? How are they handling this in their documentation? Are they even?

In short no, might be a question to ask of them or the Composer team regarding the `create-project` command.

http://book.cakephp.org/3.0/en/installation.html#installing-cakephp
https://github.com/cakephp/app#configuration

**Comment by alecho** [comment]
The `post-install-cmd` should only run once after install for that specific project.

**Comment by beporter** [comment]
Yeah but doesn't that mean _for each dev_? And that seems to imply _any_ time `composer install` is run in the future too.

**Comment by jtyost2** [comment]
Why would you run `composer install` multiple times on the skeleton (except for testing obviously)? If it runs once when whatever person creates this new project along with the repo and etc. Everyone else would then just download from the repo this new project, not re-spawn it.

**Comment by jtyost2** [comment]
Whoops hit the wrong button when commenting.

**Comment by beporter** [comment]
I think you're neglecting the fact that the composer.json will still contain those commands in the new project too.

**Comment by jtyost2** [comment]
I guess I was thinking that if we are already editing the composer.json file why would that command still be there after running the `create-project` command.

**Comment by beporter** [comment]
Yeah, there are two related things here:

1. We should probably be using `post-create-project-cmd` instead, in which case, it wouldn't be **critical** any more to remove the commands from the new project's copy of composer.json because new projects would never be spawned again from the new project itself.
2. We should still remove the keys, because the new project doesn't need to keep a now-useless `post-create-project-cmd` key around forever in its composer.json.

**Comment by alecho** [comment]
I think Justin is right here that replacing the existing composer.son with a template one solves this and other issues as well.

**Comment by beporter** [comment]
That means maintaining two entire copies of the composer.json, which is going to be a pain. It also means re-running `composer install` in the target project to catch the deps in the newly-renamed composer.json.template file. Not saying one way is better than the other, and I don't honestly know which I think is less work and less prone to error.

**Comment by alecho** [comment]
Let's do it in the `pre-install-cmd` then and everything should be fine. Also, composer files tend to be less than 50 lines long so it's really inconvenient more than anything. The skeleton's really won't matter too much in this case then.

**Comment by beporter** [comment]
Call me idealistic, but the skeleton is meant to be an example of good design and best practices. It represents the minimum standard of quality we're willing to accept. I would argue that inconveniences are not best practices. Tiny inconveniences here also multiply out to every project created from the skeleton, becoming a large collective pain the butt. 

And besides, if we're okay with them here, then why are we bothering with a skeleton designed **explicitly** to save us the repeating pain of dealing with those inconveniences on every new project?

**Comment by alecho** [comment]
I'm just talking about having to keep one version of the `composer.json` so that composer knows what to grab and a "real" `composer.json.template` that would be from what the final projects composer file is generated. No inconveniences for the generated project then.

**Comment by beporter** [comment]
There is if someone adds a dependency to composer.json thinking it's going to end up in new apps. That's a potential booby trap, which is why I'm asking if modifying a single unified file is a better choice.

Also, look at Laravel's "starter" repo for how they do this: https://github.com/laravel/laravel/blob/master/composer.json They have it broken into things to "always do on install", "always do on update" and "only do on create-project". Right now I think we need to just focus on the last one.

**Comment by beporter** [comment]
This also kind of ended up being a duplicate of #61, sorry @jtyost2.

**Comment by beporter** [comment]
I'm committing a `composer.json.template` file in #74 to start us out.

**Comment by beporter** [comment]
Closing this. our `composer.json.template` is in pretty good shape now.
