### ISSUE TITLE
Scripts not needed in created project should be removed 

### ISSUE THREAD

**Issue by alecho** [loadsys/CakePHP-Skeleton#72]
We can edit everyone else's comments so I'll start a list here for whomever grabs this issue first.

Files to be removed:
  * src/Console/LoadsysInstaller.php
  * src/Console/FileParser.php
  * src/Console/InstallerConfigurer.php
  * test-project.sh

**Comment by beporter** [comment]
The `test-project.sh` should be included in the "scripts to remove from the spawned project" list.

**Comment by beporter** [comment]
In the short term, I've solved this by adding an exception to the `FileParser` to skip any `*.template`s found inside the `/skel` directory in #146. This is crude, but effective.

Longer term, the best solution is to extract these scripts from the Skeleton itself entirely, and bundle them in the `loadsys/composer-plugins` repo instead. That would solve **all** of the problems nicely. See loadsys/composer-plugins#1 for details.

**Comment by beporter** [comment]
Closed by #149.
