### ISSUE TITLE
The Token replacement process needs to fail unlink() gracefully.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#73]
Right now, both a `filename.template` **and** a `filename` must exist. If `filename` does not exist, the `unlink()` command to remove it fails and causes the post-create-project-cmd scripts to exit out prematurely:

```
Script App\Console\LoadsysInstaller::postInstall handling the 
post-create-project-cmd event terminated with an exception


                                                                                         
  [ErrorException]                                                                       
  unlink(/Users/beporter/Desktop/newapp/puphpet/config.yaml): No such file or directory  
                                                                                         
```

It must be acceptable for there to **only** be a `filename.template` in the skeleton that will be token-replaced and renamed in the resulting app without a "skeleton-only" equivalent file existing.

**Comment by alecho** [comment]
Weird. The docs don't mention it throwing an exception: http://php.net/manual/en/function.unlink.php.

**Comment by beporter** [comment]
PHP error handlers can be configured to catch language warnings and notices and re-throw them as exceptions. That's how cake works too. Notice that it's a composer-styled message, not stock php.

**Comment by alecho** [comment]
Ah, that's it.
