### ISSUE TITLE
Better tokens with default values

### ISSUE THREAD

**Issue by alecho** [loadsys/CakePHP-Skeleton#75]
I'd like to see token be able to have a default value for when scripts are run non-interactivly or if the user is <kbd>return</kbd> happy.

I'm proposing that tokens be switched from `_{2}[A-Z0-9_]*_{2}` to  `\{{2}([A-Z0-9_]+)(:(.*))?\}{2}`. This would make tokens look like {{TOKEN:default}} or just {{TOKEN}}instead of __TOKEN__ and allow for handy default values in templates.

**Comment by beporter** [comment]
The `.*` is bad, if the match is greedy, it will grab something like this:

`Start. {{TOKEN1:default}} Some other words {{TOKEN2:foobar}}. The end.` => `default}} Some other words {{TOKEN2:foobar`

I think you want `\{{2}([A-Z0-9_]+)(:[^\}]*)?\}{2}` ?

**Comment by beporter** [comment]
Otherwise I fully endorse this idea.

**Comment by jtyost2** [comment]
Seconding the better tokens.
