### ISSUE TITLE
Offer to generate a travis encrypted GITHUB_TOKEN env var.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#79]
Currently this must be done by hand, and there was a warning in the 2.x version of the `.travis.yml` file.

If possible, I think we need a post-create-project script that checks for the `travis` command line tool and offers to generate and insert the github token for you. This doesn't need to be a ".template" thing because I think you can get the Travis command to update the `.travis.yml` file for you now.

Ref: https://github.com/loadsys/CakePHP-Skeleton/pull/67#issuecomment-72314863

**Comment by jtyost2** [comment]
Far as I can tell the only requirement for encryption is just having the `travis` gem installed.

Ref: http://docs.travis-ci.com/user/encryption-keys/#Usage

**Comment by beporter** [comment]
See also: loadsys/composer-plugins#1

**Comment by beporter** [comment]
Closed by #149
