### ISSUE TITLE
Make memcache or redis the default caching/session engine.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#81]
One of the things we're trying to do here is move our company's state of the art forward. I think one of the ways to help do that is to "mandate" (well, strongly recommend) better minimum-quality configurations. (That's what the skeleton is all about, after all.)

I'd like to suggest that the 3.0 skeleton ship with redis or memcache configured out of the box to handle sessions and caching. This would make it more likely that we'd continue to use those in production since they'd be well tested and "comfortable" configurations in development. Plus there would be less friction to **switch** to one of these because it'd already be set up.

I don't care at all which one we decide on, or even if it's something besides these two. As long as it's easy to pre-bundle in vagrant, I'm game (which is why I suggested memcache and redis).

**Comment by beporter** [comment]
@loadsys/developers:

Rebumping this question regarding the group's preference for Redis or Memcache as a superior "default" caching engine that our skeleton recommends for Cake 3 projects.

I have no strong opinion either way, so I lean towards the one that's easier to set up, maintain and secure.

Memcache for example is (decent [guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-memcache-on-ubuntu-14-04) from Digital Ocean, info on [securing](https://serverfault.com/a/347622)):

```shell
sudo apt-get install memcached php5-memcached
```

Redis seems to require building from source because the Ubuntu package (at least) is pretty old ([guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-redis), [securing](http://redis.io/topics/security)). On that alone I'd lean towards Memcache.

**Comment by joeytrapp** [comment]
:+1:

**Comment by beporter** [comment]
Ha! Well that's all the feedback I need. 😄

**Comment by jtyost2** [comment]
Considering the ease of memcache and I have no strong preference or reason to prefer one over the other, memcache is fine.

**Comment by jtyost2** [comment]
Though should add this Stackoverflow answer says, for anything new go redis: https://stackoverflow.com/questions/10558465/memcached-vs-redis

**Comment by beporter** [comment]
As a counterpoint:

http://stackoverflow.com/questions/10558465/memcached-vs-redis/11257333#comment49940780_11257333

**Comment by chronon** [comment]
I also agree with whatever is easiest to setup **and** maintain, though current Redis binary packages [are available](https://www.dotdeb.org/category/redis/) from the Dotdeb repository so building from source isn't the only option (but more cross-distribution of course).
