### ISSUE TITLE
Add Shell Scripts, ConfigReadShell, CodeSniffer to composer.json.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#88]
They currently can not be included inthe 3.0 skeleton because they don't have 3.0-compatible versions available.

See:
* loadsys/CakePHP-Shell-Scripts#36
* loadsys/CakePHP-ConfigReadShell#3 & loadsys/CakePHP-ConfigReadShell#5

Once those are closed, we can add the following into `composer.json.template`:

```json
  "require": {
    "loadsys/cakephp-shell-scripts": "3.0.*",
    "loadsys/config-read": "3.0.*"
  },
```

Then there's the code sniffer, which needs to be updated as well:

```json
  "require-dev": {
    "loadsys/loadsys_codesniffer": "2.0.*",
  },
```

(Mind the commas.)

**Comment by beporter** [comment]
@jtyost2: Plan of attack:

* Spawn a new project using the cake3 version of this skeleton.
* Edit the composer.json of the spawned project to include the problem children listed in the issue title.
* Run `composer install` and figure out what the problems or sub-dependency issues are in those projects.
* Go out to those projects, fix the "Cake 3 appropriate" branch and submit PRs.

**Comment by beporter** [comment]
I think this can be considered "complete" now, right?

**Comment by jtyost2** [comment]
Yes.
