### ISSUE TITLE
Update Packagist package name.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#98]
It's currently still published as `loadsys/app` in [our packages list](https://packagist.org/packages/loadsys/) even though the README says to use `loadsys/skeleton` and the `composer.json` also specifies `loadsys/skeleton`.

**Comment by beporter** [comment]
According to composer/packagist#47, the only way to accomplish this is to have one of the maintainers of the Packagist package delete it and re-add it with the new name. CC: @alecho & @ricog since they are the listed maintainers.

**Comment by ricog** [comment]
I made the change on packagist and added @alecho and @beporter as maintainers. https://packagist.org/packages/loadsys/skeleton
